apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperclip.serverService" . }}-data
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | quote }}
